// utils/profession/bullets.ts
// ============================================
// PROFESSION BULLETS - 60+ Professions
// ============================================

import { getDoctorBullets } from '../pools/doctorPool';
import { getTeacherBullets } from '../pools/teacherPool';
import { getDeveloperBullets } from '../pools/developerPool';
import { getBusinessBullets } from '../pools/businessPool';
import { getEngineeringBullets } from '../pools/engineeringPool';
import { getAccountantBullets } from '../pools/accountantPool';
import { getSalesBullets } from '../pools/salesPool';
import { getHrBullets } from '../pools/hrPool';
import { getDesignerBullets } from '../pools/designerPool';
import { getLawBullets } from '../pools/lawPool';
import { getSocialSciencesBullets } from '../pools/socialSciencesPool';
import { getNaturalSciencesBullets } from '../pools/naturalSciencesPool';
import { getArtsBullets } from '../pools/artsPool';
import { getGeneralBullets } from '../pools/generalPool';
import { getDataScientistBullets } from '../pools/dataScientistPool';
import { getCybersecurityBullets } from '../pools/cybersecurityPool';
import { getCloudEngineerBullets } from '../pools/cloudEngineerPool';
import { getDevopsBullets } from '../pools/devopsPool';
import { getProductManagerBullets } from '../pools/productManagerPool';
import { getProjectManagerBullets } from '../pools/projectManagerPool';
import { getMarketingBullets } from '../pools/marketingPool';
import { getContentCreatorBullets } from '../pools/contentCreatorPool';
import { getUiuxDesignerBullets } from '../pools/uiuxDesignerPool';
import { getEntrepreneurBullets } from '../pools/entrepreneurPool';
import { getFreelancerBullets } from '../pools/freelancerPool';
import { getAiMlEngineerBullets } from '../pools/aiMlEngineerPool';
import { getFrontendDeveloperBullets } from '../pools/frontendDeveloperPool';
import { getBackendDeveloperBullets } from '../pools/backendDeveloperPool';
import { getFullStackDeveloperBullets } from '../pools/fullStackDeveloperPool';
import { getGraphicDesignerBullets } from '../pools/graphicDesignerPool';
import { getNurseBullets } from '../pools/nursePool';
import { getDataAnalystBullets } from '../pools/dataAnalystPool';
import { getBusinessAnalystBullets } from '../pools/businessAnalystPool';
import { getBankerBullets } from '../pools/bankerPool';
import { getDentistBullets } from '../pools/dentistPool';
import { getPharmacistBullets } from '../pools/pharmacistPool';
import { getPilotBullets } from '../pools/pilotPool';
import { getArmyOfficerBullets } from '../pools/armyOfficerPool';
import { getItSupportBullets } from '../pools/itSupportPool';
import { getProfessorBullets } from '../pools/professorPool';
import { getOperationsManagerBullets } from '../pools/operationsManagerPool';
import { getGameDeveloperBullets } from '../pools/gameDeveloperPool';
import { getSolarPVInstallerBullets } from '../pools/solarPVInstallerPool';
import { getWindTurbineTechnicianBullets } from '../pools/windTurbineTechnicianPool';
import { getRenewableEnergyEngineerBullets } from '../pools/renewableEnergyEngineerPool';
import { getSeoSpecialistBullets } from '../pools/seoSpecialistPool';
import { getPerformanceMarketerBullets } from '../pools/performanceMarketerPool';
import { getElectricianBullets } from '../pools/electricianPool';
import { getPlumberBullets } from '../pools/plumberPool';
import { getPhysicsTeacherBullets } from '../pools/physicsTeacherPool';
import { getChemistryTeacherBullets } from '../pools/chemistryTeacherPool';
import { getMathTeacherBullets } from '../pools/mathTeacherPool';
import { getBiologyTeacherBullets } from '../pools/biologyTeacherPool';
import { getEnglishTeacherBullets } from '../pools/englishTeacherPool';
import { getUrduTeacherBullets } from '../pools/urduTeacherPool';
import { getComputerTeacherBullets } from '../pools/computerTeacherPool';
import { getIslamicStudiesTeacherBullets } from '../pools/islamicStudiesTeacherPool';
import { getPakistanStudiesTeacherBullets } from '../pools/pakistanStudiesTeacherPool';
import { getHistoryTeacherBullets } from '../pools/historyTeacherPool';

export const getBulletsByProfession = (profession: string, level: string, company: string): string[] => {
    const levelKey = level === 'director' || level === 'manager' ? 'senior' : level;
    
    switch (profession) {
        case 'doctor': return getDoctorBullets(levelKey, company);
        case 'teacher': return getTeacherBullets(levelKey, company);
        case 'developer': return getDeveloperBullets(levelKey, company);
        case 'business': return getBusinessBullets(levelKey, company);
        case 'engineering': return getEngineeringBullets(levelKey, company);
        case 'accountant': return getAccountantBullets(levelKey, company);
        case 'sales': return getSalesBullets(levelKey, company);
        case 'hr': return getHrBullets(levelKey, company);
        case 'designer': return getDesignerBullets(levelKey, company);
        case 'law': return getLawBullets(levelKey, company);
        case 'social-sciences': return getSocialSciencesBullets(levelKey, company);
        case 'natural-sciences': return getNaturalSciencesBullets(levelKey, company);
        case 'arts': return getArtsBullets(levelKey, company);
        case 'data-scientist': return getDataScientistBullets(levelKey, company);
        case 'cybersecurity': return getCybersecurityBullets(levelKey, company);
        case 'cloud': return getCloudEngineerBullets(levelKey, company);
        case 'devops': return getDevopsBullets(levelKey, company);
        case 'product-manager': return getProductManagerBullets(levelKey, company);
        case 'project-manager': return getProjectManagerBullets(levelKey, company);
        case 'marketing': return getMarketingBullets(levelKey, company);
        case 'content-creator': return getContentCreatorBullets(levelKey, company);
        case 'uiux': return getUiuxDesignerBullets(levelKey, company);
        case 'entrepreneur': return getEntrepreneurBullets(levelKey, company);
        case 'freelancer': return getFreelancerBullets(levelKey, company);
        case 'ai-ml': return getAiMlEngineerBullets(levelKey, company);
        case 'frontend': return getFrontendDeveloperBullets(levelKey, company);
        case 'backend': return getBackendDeveloperBullets(levelKey, company);
        case 'full-stack': return getFullStackDeveloperBullets(levelKey, company);
        case 'graphic-designer': return getGraphicDesignerBullets(levelKey, company);
        case 'nurse': return getNurseBullets(levelKey, company);
        case 'data-analyst': return getDataAnalystBullets(levelKey, company);
        case 'business-analyst': return getBusinessAnalystBullets(levelKey, company);
        case 'banker': return getBankerBullets(levelKey, company);
        case 'dentist': return getDentistBullets(levelKey, company);
        case 'pharmacist': return getPharmacistBullets(levelKey, company);
        case 'pilot': return getPilotBullets(levelKey, company);
        case 'army': return getArmyOfficerBullets(levelKey, company);
        case 'it-support': return getItSupportBullets(levelKey, company);
        case 'professor': return getProfessorBullets(levelKey, company);
        case 'operations-manager': return getOperationsManagerBullets(levelKey, company);
        case 'game-developer': return getGameDeveloperBullets(levelKey, company);
        case 'renewable': return getRenewableEnergyEngineerBullets(levelKey, company);
        case 'solar': return getSolarPVInstallerBullets(levelKey, company);
        case 'wind': return getWindTurbineTechnicianBullets(levelKey, company);
        case 'digital-marketing': return getPerformanceMarketerBullets(levelKey, company);
        case 'seo': return getSeoSpecialistBullets(levelKey, company);
        case 'vocational': return getElectricianBullets(levelKey, company);
        case 'electrician': return getElectricianBullets(levelKey, company);
        case 'plumber': return getPlumberBullets(levelKey, company);
        case 'physics-teacher': return getPhysicsTeacherBullets(levelKey, company);
        case 'chemistry-teacher': return getChemistryTeacherBullets(levelKey, company);
        case 'math-teacher': return getMathTeacherBullets(levelKey, company);
        case 'biology-teacher': return getBiologyTeacherBullets(levelKey, company);
        case 'english-teacher': return getEnglishTeacherBullets(levelKey, company);
        case 'urdu-teacher': return getUrduTeacherBullets(levelKey, company);
        case 'computer-teacher': return getComputerTeacherBullets(levelKey, company);
        case 'islamic-studies-teacher': return getIslamicStudiesTeacherBullets(levelKey, company);
        case 'pakistan-studies-teacher': return getPakistanStudiesTeacherBullets(levelKey, company);
        case 'history-teacher': return getHistoryTeacherBullets(levelKey, company);
        default: return getGeneralBullets(levelKey, company);
    }
};