import { 
    ExperienceItem, EducationItem, ProjectItem, 
    CertificationItem, LanguageItem, AchievementItem 
} from '../types/cvTypes';

export interface CVData {
    personalInfo: any;
    phoneNumber: string;
    selectedCountryCode: string;
    professionalSummary: string;
    experiences: ExperienceItem[];
    educations: EducationItem[];
    projects: ProjectItem[];
    certifications: CertificationItem[];
    languages: LanguageItem[];
    achievements: AchievementItem[];
    skills: string;
}

export const generatePlainTextCV = (data: CVData): string => {
    const {
        personalInfo,
        phoneNumber,
        selectedCountryCode,
        professionalSummary,
        experiences,
        educations,
        projects,
        certifications,
        languages,
        achievements,
        skills
    } = data;

    let text = `${personalInfo.name?.toUpperCase() || 'YOUR NAME'}\n`;
    text += `${'='.repeat(60)}\n`;
    text += `${personalInfo.title || 'JOB TITLE'}\n\n`;
    
    // Contact Information
    text += `CONTACT INFORMATION\n${'-'.repeat(40)}\n`;
    if (personalInfo.email) text += `Email: ${personalInfo.email}\n`;
    if (phoneNumber) text += `Phone: ${selectedCountryCode} ${phoneNumber}\n`;
    if (personalInfo.address) text += `Address: ${personalInfo.address}\n`;
    if (personalInfo.linkedin) text += `LinkedIn: ${personalInfo.linkedin}\n`;
    if (personalInfo.github) text += `GitHub: ${personalInfo.github}\n`;
    text += `\n`;
    
    // Professional Summary
    if (professionalSummary) {
        text += `PROFESSIONAL SUMMARY\n${'-'.repeat(40)}\n${professionalSummary}\n\n`;
    }
    
    // Work Experience
    const validExperiences = experiences.filter(e => e.title?.trim() && e.company?.trim());
    if (validExperiences.length > 0) {
        text += `WORK EXPERIENCE\n${'-'.repeat(40)}\n`;
        validExperiences.forEach((exp, idx) => {
            text += `${idx + 1}. ${exp.title} at ${exp.company}\n`;
            if (exp.startDate || exp.endDate) {
                text += `   ${exp.startDate || 'Start'} - ${exp.endDate || 'Present'}\n`;
            }
            if (exp.description) {
                text += `   ${exp.description.replace(/\n/g, '\n   ')}\n\n`;
            }
        });
    }
    
    // Education
    const validEducations = educations.filter(e => e.degree?.trim() && e.institution?.trim());
    if (validEducations.length > 0) {
        text += `EDUCATION\n${'-'.repeat(40)}\n`;
        validEducations.forEach((edu, idx) => {
            text += `${idx + 1}. ${edu.degree}\n`;
            text += `   Institution: ${edu.institution}\n`;
            if (edu.year) text += `   ${edu.year}\n`;
            if (edu.grade) text += `   Grade: ${edu.grade}\n\n`;
        });
    }
    
    // Languages
    const validLanguages = languages.filter(l => l.language?.trim());
    if (validLanguages.length > 0) {
        text += `LANGUAGES\n${'-'.repeat(40)}\n`;
        validLanguages.forEach((lang, idx) => {
            text += `${idx + 1}. ${lang.language} - ${lang.proficiency}\n`;
        });
        text += `\n`;
    }
    
    // Projects
    const validProjects = projects.filter(p => p.name?.trim());
    if (validProjects.length > 0) {
        text += `PROJECTS\n${'-'.repeat(40)}\n`;
        validProjects.forEach((p, idx) => {
            text += `${idx + 1}. ${p.name}\n`;
            if (p.tech) text += `   Technologies: ${p.tech}\n`;
            if (p.description) text += `   Description: ${p.description}\n`;
            if (p.github) text += `   GitHub: ${p.github}\n\n`;
        });
    }
    
    // Skills
    if (skills?.trim()) {
        text += `SKILLS\n${'-'.repeat(40)}\n`;
        const skillArray = skills.includes(',') 
            ? skills.split(',').map(s => s.trim()).filter(s => s)
            : skills.split('\n').map(s => s.trim().replace(/^[•\-*]\s*/, '')).filter(s => s);
        skillArray.forEach(skill => { text += `• ${skill}\n`; });
        text += `\n`;
    }
    
    text += `${'='.repeat(60)}\n`;
    text += `Generated by Adin AI CV Builder\n`;
    
    return text;
};

export const getFileName = (name: string, extension: string): string => {
    const sanitizedName = name.replace(/\s/g, '_') || 'MyCV';
    return `CV_${sanitizedName}.${extension}`;
};

export const downloadBlob = (content: string | Blob, fileName: string, mimeType: string) => {
    const blob = content instanceof Blob ? content : new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

export const copyToClipboard = async (text: string): Promise<boolean> => {
    try {
        await navigator.clipboard.writeText(text);
        return true;
    } catch {
        return false;
    }
};